name: Publish release

on:
  push:
    tags:
      - "**"

jobs:
  publish-release:
    name: "Publish release"
    permissions:
      contents: write
    uses: "GabrieleBocchi/plugin-release-workflows/.github/workflows/publish-release.yml@75e33a4b10f7816c3054be2461dbf9ee748b6f68" # improve-security-release-workflows
