name: Continuous integration

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-ci-matrix:
    name: Generate CI matrix
    uses: GabrieleBocchi/plugin-ci-workflows/.github/workflows/generate-ci-matrix.yml@7da90f89e332154dbd478a43e7b4163857cb84b7 # improve-security-ci-workflows
    with:
      glpi-version: "12.0.x"
  ci:
    name: "GLPI ${{ matrix.glpi-version }} - php:${{ matrix.php-version }} - ${{ matrix.db-image }}"
    needs: generate-ci-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-ci-matrix.outputs.matrix) }}
    uses: GabrieleBocchi/plugin-ci-workflows/.github/workflows/continuous-integration.yml@7da90f89e332154dbd478a43e7b4163857cb84b7 # improve-security-ci-workflows
    with:
      plugin-key: inventorymultitenancy
      glpi-version: ${{ matrix.glpi-version }}
      php-version: ${{ matrix.php-version }}
      db-image: ${{ matrix.db-image }}
      init-script: "./.github/workflows/init-script.sh"
      extra-services: "openldap"
      run-e2e-tests: ${{ matrix.run-e2e-tests }}
    secrets:
      extra-env: |
        PLUGIN_INVENTORYMULTITENANCY_CI_EXTRA_ENV=loaded
  coverage-report:
    name: Coverage report
    needs: ci
    permissions:
      actions: read
      pull-requests: write
    uses: GabrieleBocchi/plugin-ci-workflows/.github/workflows/coverage-report.yml@7da90f89e332154dbd478a43e7b4163857cb84b7 # improve-security-ci-workflows
    with:
      plugin-key: inventorymultitenancy
